language: java
jdk: oraclejdk8
sudo: false
install: true
script: mvn clean verify
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
 directories:
   - $HOME/.m2
before_install:
  - chmod +x mvnw