language: java
jdk: oraclejdk8
sudo: false
install: true
# script: mvn clean verify
script: "mvn cobertura:cobertura"
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
 directories:
   - $HOME/.m2
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)